export const AUDIT_ADMIN_FILTERS = [
  "All",
  "Elena Fischer",
  "Mira Roth",
  "Marc Steiner",
  "Nadia Frei",
];

export const AUDIT_MODULE_FILTERS = [
  "All",
  "Plans",
  "Customers",
  "eSIM Management",
  "Billing",
  "Admin Users",
];

export const AUDIT_ACTION_FILTERS = [
  "All",
  "Plan updates",
  "Customer suspension",
  "eSIM activation",
  "Invoice creation",
  "Admin login",
];

export const AUDIT_LOGS_DATA = [
  {
    id: "log-1",
    dateTime: "2026-02-12 09:19",
    admin: "Elena Fischer",
    action: "Plan updates",
    module: "Plans",
    target: "Nova Swiss+",
    ipActivity: "194.230.16.10",
    status: "Success",
    details: "Updated pricing tiers and data allowance parameters for Nova Swiss+.",
  },
  {
    id: "log-2",
    dateTime: "2026-02-15 18:05",
    admin: "Mira Roth",
    action: "Customer suspension",
    module: "Customers",
    target: "Jonas Baumann",
    ipActivity: "194.230.16.44",
    status: "Success",
    details: "Account line suspended due to repeated overdue billing statements.",
  },
  {
    id: "log-3",
    dateTime: "2026-02-16 11:42",
    admin: "Marc Steiner",
    action: "eSIM activation",
    module: "eSIM Management",
    target: "ES-4004",
    ipActivity: "194.230.16.13",
    status: "Failed",
    details: "eSIM provisioning failed with error code 503 Carrier Timeout.",
  },
  {
    id: "log-4",
    dateTime: "2026-02-17 16:20",
    admin: "Nadia Frei",
    action: "Invoice creation",
    module: "Billing",
    target: "INV-9034",
    ipActivity: "194.230.16.22",
    status: "Success",
    details: "Generated invoice INV-9034 for CHF 89.00 sent to customer email.",
  },
  {
    id: "log-5",
    dateTime: "2026-02-18 08:45",
    admin: "Elena Fischer",
    action: "Admin login",
    module: "Admin Users",
    target: "Elena Fischer",
    ipActivity: "194.230.16.10",
    status: "Success",
    details: "Successful login via 2-factor authentication from Zurich office.",
  },
  {
    id: "log-6",
    dateTime: "2026-02-19 14:10",
    admin: "Marc Steiner",
    action: "Plan updates",
    module: "Plans",
    target: "Nova Global Unlimited",
    ipActivity: "194.230.16.13",
    status: "Success",
    details: "Added 10 new roaming country destinations to standard package.",
  },
];
