export const COMMISSION_STAT_CARDS = [
  {
    id: "total-earnings",
    label: "Total Earnings",
    value: "CHF 275.00",
    iconType: "dollar",
    iconBg: "bg-purple-50 text-purple-600",
  },
  {
    id: "this-month",
    label: "This Month",
    value: "CHF 335.00",
    iconType: "trending",
    iconBg: "bg-sky-50 text-sky-500",
  },
  {
    id: "pending-commission",
    label: "Pending Commission",
    value: "CHF 35.00",
    iconType: "clock",
    iconBg: "bg-amber-50 text-amber-500",
  },
  {
    id: "paid-commission",
    label: "Paid Commission",
    value: "CHF 275.00",
    iconType: "check",
    iconBg: "bg-emerald-50 text-emerald-500",
  },
];

export const COMMISSIONS_CHART_DATA = [
  { month: "Jan", revenue: 16000 },
  { month: "Feb", revenue: 20000 },
  { month: "Mar", revenue: 18000 },
  { month: "Apr", revenue: 26000 },
  { month: "May", revenue: 32000 },
  { month: "Jun", revenue: 35600 },
  { month: "Jul", revenue: 38000 },
  { month: "Aug", revenue: 31000 },
  { month: "Sep", revenue: 37000 },
  { month: "Oct", revenue: 42000 },
  { month: "Nov", revenue: 41000 },
  { month: "Dec", revenue: 46000 },
];

export const COMMISSION_DETAILS_DATA = [
  {
    id: "cd-1",
    customer: "John Smith",
    order: "ORD-2026-001",
    plan: "NovaSky Plus",
    commission: "CHF 60.00",
    status: "Paid",
    date: "Aug 13, 2026",
  },
  {
    id: "cd-2",
    customer: "Anna Müller",
    order: "ORD-2026-002",
    plan: "NovaSky Max",
    commission: "CHF 90.00",
    status: "Paid",
    date: "Aug 11, 2026",
  },
  {
    id: "cd-3",
    customer: "Marco Rossi",
    order: "ORD-2026-003",
    plan: "NovaSky One",
    commission: "CHF 35.00",
    status: "Pending",
    date: "Aug 15, 2026",
  },
  {
    id: "cd-4",
    customer: "Sophie Bernard",
    order: "ORD-2026-004",
    plan: "NovaSky Plus",
    commission: "CHF 60.00",
    status: "Paid",
    date: "Aug 14, 2026",
  },
  {
    id: "cd-5",
    customer: "Thomas Weber",
    order: "ORD-2026-005",
    plan: "NovaSky Max",
    commission: "CHF 90.00",
    status: "Paid",
    date: "Aug 9, 2026",
  },
  {
    id: "cd-6",
    customer: "Léa Dubois",
    order: "ORD-2026-006",
    plan: "NovaSky One",
    commission: "CHF 35.00",
    status: "Paid",
    date: "Aug 6, 2026",
  },
];
