export const COLLABORATOR_CUSTOMERS_DATA = [
  {
    id: "cust-1",
    profileId: "C-1001",
    customer: "Amina Rossi",
    email: "amina.rossi@example.ch",
    phone: "+41 78 441 88 44",
    customerType: "Private",
    plan: "NovaSky Max",
    simType: "Physical SIM",
    usage: "14.2 GB of 50 GB",
    lineStatus: "Active",
    registrationDate: "2026-02-11",
    status: "Active",
    invoice: "INV-9028",
    paymentHistory: "CHF 59.90 paid on 2026-02-11",
  },
  {
    id: "cust-2",
    profileId: "C-1002",
    customer: "Claire Dubois",
    email: "claire.dubois@example.ch",
    phone: "+41 78 884 50 91",
    customerType: "Private",
    plan: "NovaSky Plus",
    simType: "eSIM",
    usage: "11.2 GB of 40 GB",
    lineStatus: "Active",
    registrationDate: "2026-02-03",
    status: "Active",
    invoice: "INV-9029",
    paymentHistory: "CHF 49.90 paid on 2026-02-03",
  },
  {
    id: "cust-3",
    profileId: "C-1003",
    customer: "Jonas Baumann",
    email: "jonas.baumann@example.ch",
    phone: "+41 77 109 28 72",
    customerType: "Private",
    plan: "NovaSky One",
    simType: "Physical SIM",
    usage: "5.0 GB of 20 GB",
    lineStatus: "Suspended",
    registrationDate: "2025-11-09",
    status: "Suspended",
    invoice: "INV-9012",
    paymentHistory: "CHF 39.90 paid on 2025-11-09",
  },
  {
    id: "cust-4",
    profileId: "C-1004",
    customer: "Lena Meier",
    email: "lena.meier@example.ch",
    phone: "+41 79 224 11 03",
    customerType: "Private",
    plan: "NovaSky Plus",
    simType: "eSIM",
    usage: "14.8 GB of 40 GB",
    lineStatus: "Active",
    registrationDate: "2026-01-12",
    status: "Active",
    invoice: "INV-9022",
    paymentHistory: "CHF 49.90 paid on 2026-01-12",
  },
  {
    id: "cust-5",
    profileId: "C-1005",
    customer: "Marco Keller",
    email: "marco.keller@example.ch",
    phone: "+41 78 330 22 18",
    customerType: "Business",
    plan: "NovaSky Max",
    simType: "eSIM",
    usage: "22.4 GB of 50 GB",
    lineStatus: "Active",
    registrationDate: "2025-12-30",
    status: "Active",
    invoice: "INV-9018",
    paymentHistory: "CHF 59.90 paid on 2025-12-30",
  },
  {
    id: "cust-6",
    profileId: "C-1006",
    customer: "Sophie Bernard",
    email: "sophie.bernard@example.ch",
    phone: "+41 76 901 33 55",
    customerType: "Private",
    plan: "NovaSky Plus",
    simType: "Physical SIM",
    usage: "19.0 GB of 40 GB",
    lineStatus: "Active",
    registrationDate: "2025-12-30",
    status: "Active",
    invoice: "INV-8980",
    paymentHistory: "CHF 49.90 paid on 2025-12-30",
  },
  {
    id: "cust-7",
    profileId: "C-1007",
    customer: "Thomas Weber",
    email: "t.weber@example.ch",
    phone: "+41 79 552 14 80",
    customerType: "Private",
    plan: "NovaSky Max",
    simType: "eSIM",
    usage: "8.1 GB of 50 GB",
    lineStatus: "Active",
    registrationDate: "2025-12-30",
    status: "Active",
    invoice: "INV-8994",
    paymentHistory: "CHF 59.90 paid on 2025-12-30",
  },
];

export const COLLABORATOR_STATUS_OPTIONS = ["All", "Active", "Suspended"];

export const COLLABORATOR_PLAN_OPTIONS = [
  "All",
  "NovaSky Max",
  "NovaSky Plus",
  "NovaSky One",
];

export const COLLABORATOR_SIM_TYPE_OPTIONS = ["Physical SIM", "eSIM"];

export const COLLABORATOR_CUSTOMER_ACTIONS = [
  { label: "See Details", isPrimary: true, action: "details" },
  { label: "Edit", action: "edit" },
  { label: "Orders", action: "orders" },
  { label: "Activations", action: "activations" },
];
