export const ORDERS_DATA = [
  {
    id: "ord-1",
    orderId: "BK-001",
    customer: "Albert Flores",
    plan: "NovaSky One",
    simType: "eSIM",
    orderDate: "07/08/2026",
    status: "Pending",
  },
  {
    id: "ord-2",
    orderId: "BK-002",
    customer: "Marvin McKinney",
    plan: "NovaSky Plus",
    simType: "eSIM",
    orderDate: "07/08/2026",
    status: "Identity Verification",
  },
  {
    id: "ord-3",
    orderId: "BK-003",
    customer: "Dianne Russell",
    plan: "NovaSky Max",
    simType: "eSIM",
    orderDate: "07/08/2026",
    status: "Approved",
  },
  {
    id: "ord-4",
    orderId: "BK-004",
    customer: "Cameron Williamson",
    plan: "NovaSky Max",
    simType: "eSIM",
    orderDate: "07/08/2026",
    status: "Approved",
  },
  {
    id: "ord-5",
    orderId: "BK-005",
    customer: "Robert Fox",
    plan: "NovaSky Max",
    simType: "eSIM",
    orderDate: "07/08/2026",
    status: "Activated",
  },
  {
    id: "ord-6",
    orderId: "BK-006",
    customer: "Jane Cooper",
    plan: "NovaSky Max",
    simType: "eSIM",
    orderDate: "07/08/2026",
    status: "Rejected",
  },
  {
    id: "ord-7",
    orderId: "BK-007",
    customer: "Brooklyn Simmons",
    plan: "NovaSky Max",
    simType: "eSIM",
    orderDate: "07/08/2026",
    status: "Rejected",
  },
  {
    id: "ord-8",
    orderId: "BK-008",
    customer: "Wade Warren",
    plan: "NovaSky Max",
    simType: "eSIM",
    orderDate: "07/08/2026",
    status: "Activated",
  },
  {
    id: "ord-9",
    orderId: "BK-009",
    customer: "Jerome Bell",
    plan: "NovaSky Plus",
    simType: "eSIM",
    orderDate: "07/08/2026",
    status: "Approved",
  },
  {
    id: "ord-10",
    orderId: "BK-010",
    customer: "Jacob Jones",
    plan: "NovaSky Plus",
    simType: "eSIM",
    orderDate: "07/08/2026",
    status: "Activated",
  },
];

export const ORDER_COLUMNS = [
  { key: "orderId", label: "Order ID", className: "font-semibold text-slate-900" },
  { key: "customer", label: "Customer", className: "text-slate-800 font-medium" },
  { key: "plan", label: "Plan", className: "text-sky-700 font-medium" },
  { key: "simType", label: "SIM type", className: "text-slate-600" },
  { key: "orderDate", label: "Order date", className: "font-mono text-slate-600" },
  { key: "status", label: "Status", isStatus: true },
  { key: "action", label: "Action", align: "right" },
];

export const ORDER_ACTIONS = [
  { label: "See Details", isPrimary: true, action: "details" },
  { label: "Pending", action: "status_pending" },
  { label: "Identity Verification", action: "status_verification" },
  { label: "Approved", action: "status_approved" },
  { label: "Activated", action: "status_activated" },
  { label: "Rejected", action: "status_rejected" },
];

export const ORDER_STATUS_FILTERS = [
  "All Statuses",
  "Pending",
  "Identity Verification",
  "Approved",
  "Activated",
  "Rejected",
];
