export const ESIM_STATUS_FILTERS = [
  "All Statuses",
  "Active",
  "Pending",
  "Suspended",
  "Reissue",
  "Generated",
  "Failed",
];

export const ESIM_PROFILES_DATA = [
  {
    id: "esim-1",
    customer: "Albert Flores",
    documentType: "National ID Card",
    esimStatus: "Suspended",
    activationDate: "07/08/2026",
    qrStatus: "Pending",
  },
  {
    id: "esim-2",
    customer: "Marvin McKinney",
    documentType: "Driving License",
    esimStatus: "Active",
    activationDate: "07/08/2026",
    qrStatus: "Generated",
  },
  {
    id: "esim-3",
    customer: "Dianne Russell",
    documentType: "Driving License",
    esimStatus: "Pending",
    activationDate: "07/08/2026",
    qrStatus: "Generated",
  },
  {
    id: "esim-4",
    customer: "Cameron Williamson",
    documentType: "Driving License",
    esimStatus: "Active",
    activationDate: "07/08/2026",
    qrStatus: "Generated",
  },
  {
    id: "esim-5",
    customer: "Robert Fox",
    documentType: "National ID Card",
    esimStatus: "Reissue",
    activationDate: "07/08/2026",
    qrStatus: "Failed",
  },
  {
    id: "esim-6",
    customer: "Jane Cooper",
    documentType: "National ID Card",
    esimStatus: "Active",
    activationDate: "07/08/2026",
    qrStatus: "Generated",
  },
  {
    id: "esim-7",
    customer: "Brooklyn Simmons",
    documentType: "National ID Card",
    esimStatus: "Suspended",
    activationDate: "07/08/2026",
    qrStatus: "Generated",
  },
  {
    id: "esim-8",
    customer: "Wade Warren",
    documentType: "Driving License",
    esimStatus: "Active",
    activationDate: "07/08/2026",
    qrStatus: "Generated",
  },
  {
    id: "esim-9",
    customer: "Jerome Bell",
    documentType: "National ID Card",
    esimStatus: "Reissue",
    activationDate: "07/08/2026",
    qrStatus: "Failed",
  },
  {
    id: "esim-10",
    customer: "Jacob Jones",
    documentType: "Driving License",
    esimStatus: "Active",
    activationDate: "07/08/2026",
    qrStatus: "Generated",
  },
];

export const ESIM_ACTIONS = [
  { label: "See Details", isPrimary: true, action: "details" },
  { label: "Suspend", action: "suspend" },
  { label: "Active", action: "active" },
  { label: "Pending", action: "pending" },
  { label: "Reissue", action: "reissue" },
  { label: "Generated", action: "generated" },
  { label: "Failed", action: "failed" },
];
