export const USER_ROLES = [
  "Super Admin",
  "Manager",
  "Support Agent",
  "Marketing",
  "Finance",
  "Auditor",
];

export const USERS_DATA = [
  {
    id: "usr-1",
    name: "Darlene Robertson",
    email: "nevaeh.simmons@example.com",
    access: "Overview",
    role: "Super Admin",
    status: "Active",
    loginDate: "07/08/2026",
  },
  {
    id: "usr-2",
    name: "Arlene McCoy",
    email: "sara.cruz@example.com",
    access: "Access",
    role: "Marketing",
    status: "Disabled",
    loginDate: "07/08/2026",
  },
  {
    id: "usr-3",
    name: "Eleanor Pena",
    email: "curtis.weaver@example.com",
    access: "Orders",
    role: "Manager",
    status: "Active",
    loginDate: "07/08/2026",
  },
  {
    id: "usr-4",
    name: "Brooklyn Simmons",
    email: "michael.mitc@example.com",
    access: "Identity Verification",
    role: "Support Agent",
    status: "Active",
    loginDate: "07/08/2026",
  },
  {
    id: "usr-5",
    name: "Robert Fox",
    email: "jackson.graham@example.com",
    access: "Report & Analytics",
    role: "Finance",
    status: "Active",
    loginDate: "07/08/2026",
  },
  {
    id: "usr-6",
    name: "Jane Cooper",
    email: "jane.cooper@example.com",
    access: "Customer",
    role: "Support Agent",
    status: "Active",
    loginDate: "07/08/2026",
  },
  {
    id: "usr-7",
    name: "Wade Warren",
    email: "wade.warren@example.com",
    access: "eSIM Management",
    role: "Manager",
    status: "Active",
    loginDate: "07/08/2026",
  },
];
