export const SUPPORT_PRIORITY_FILTERS = [
  "All Priority",
  "High",
  "Medium",
  "Low",
];

export const SUPPORT_STATUS_FILTERS = [
  "All Statuses",
  "Pending",
  "Open",
  "Closed",
];

export const SUPPORT_TICKETS_DATA = [
  {
    id: "tck-1",
    ticketId: "TCK-5012",
    customer: "Albert Flores",
    subject: "eSIM QR code failed",
    priority: "High",
    status: "Pending",
    assignedAgent: "Wade Warren",
    activationDate: "07/08/2026",
  },
  {
    id: "tck-2",
    ticketId: "TCK-5011",
    customer: "Marvin McKinney",
    subject: "Question about roaming package",
    priority: "Low",
    status: "Closed",
    assignedAgent: "Darrell Steward",
    activationDate: "07/08/2026",
  },
  {
    id: "tck-3",
    ticketId: "TCK-5010",
    customer: "Dianne Russell",
    subject: "Payment confirmation",
    priority: "Medium",
    status: "Open",
    assignedAgent: "Courtney Henry",
    activationDate: "07/08/2026",
  },
  {
    id: "tck-4",
    ticketId: "TCK-509",
    customer: "Cameron Williamson",
    subject: "Add a second business line",
    priority: "Medium",
    status: "Open",
    assignedAgent: "Leslie Alexander",
    activationDate: "07/08/2026",
  },
  {
    id: "tck-5",
    ticketId: "TCK-508",
    customer: "Robert Fox",
    subject: "eSIM QR code failed",
    priority: "Low",
    status: "Pending",
    assignedAgent: "Robert Fox",
    activationDate: "07/08/2026",
  },
  {
    id: "tck-6",
    ticketId: "TCK-507",
    customer: "Jane Cooper",
    subject: "Add a second business line",
    priority: "High",
    status: "Closed",
    assignedAgent: "Bessie Cooper",
    activationDate: "07/08/2026",
  },
  {
    id: "tck-7",
    ticketId: "TCK-506",
    customer: "Brooklyn Simmons",
    subject: "Add a second business line",
    priority: "High",
    status: "Pending",
    assignedAgent: "Albert Flores",
    activationDate: "07/08/2026",
  },
  {
    id: "tck-8",
    ticketId: "TCK-505",
    customer: "Wade Warren",
    subject: "Add a second business line",
    priority: "Low",
    status: "Closed",
    assignedAgent: "Cody Fisher",
    activationDate: "07/08/2026",
  },
  {
    id: "tck-9",
    ticketId: "TCK-504",
    customer: "Jerome Bell",
    subject: "Add a second business line",
    priority: "Medium",
    status: "Pending",
    assignedAgent: "Jane Cooper",
    activationDate: "07/08/2026",
  },
  {
    id: "tck-10",
    ticketId: "TCK-503",
    customer: "Jacob Jones",
    subject: "Add a second business line",
    priority: "High",
    status: "Pending",
    assignedAgent: "Dianne Russell",
    activationDate: "07/08/2026",
  },
];

export const SUPPORT_ACTIONS = [
  { label: "See Details", isPrimary: true, action: "details" },
  { label: "Assigned", action: "assigned" },
  { label: "Reply", action: "reply" },
  { label: "Closed", action: "closed" },
  { label: "High", action: "priority_high" },
  { label: "Low", action: "priority_low" },
  { label: "Pending", action: "status_pending" },
  { label: "Open", action: "status_open" },
  { label: "Closed", action: "status_closed" },
];
