export const NOTIFICATION_TYPE_FILTERS = [
  "All Types",
  "Email",
  "Sms",
  "Push",
];

export const NOTIFICATIONS_DATA = [
  {
    id: "ntf-1",
    ntfId: "NTF-6101",
    audience: "Individual Customer",
    subject: "eSIM QR code failed",
    type: "Email",
    status: "Sent",
    date: "07/08/2026",
    message: "Your eSIM profile QR code has been regenerated and is ready for activation.",
  },
  {
    id: "ntf-2",
    ntfId: "NTF-6102",
    audience: "All Customer",
    subject: "Question about roaming package",
    type: "Sms",
    status: "Sent",
    date: "07/08/2026",
    message: "Special summer roaming packages are now available across 150+ countries.",
  },
  {
    id: "ntf-3",
    ntfId: "NTF-6103",
    audience: "All Customer",
    subject: "Payment confirmation",
    type: "Push",
    status: "Sent",
    date: "07/08/2026",
    message: "Monthly billing statements have been generated for all active subscribers.",
  },
  {
    id: "ntf-4",
    ntfId: "NTF-6104",
    audience: "Individual Customer",
    subject: "Add a second business line",
    type: "Push",
    status: "Sent",
    date: "07/08/2026",
    message: "Exclusive 20% discount when adding a second business eSIM line.",
  },
  {
    id: "ntf-5",
    ntfId: "NTF-6105",
    audience: "Individual Customer",
    subject: "eSIM QR code failed",
    type: "Sms",
    status: "Sent",
    date: "07/08/2026",
    message: "Your line status has been refreshed by our automated provisioning engine.",
  },
  {
    id: "ntf-6",
    ntfId: "NTF-6106",
    audience: "All Customer",
    subject: "Network upgrade in Zurich",
    type: "Email",
    status: "Sent",
    date: "2026-02-10",
    message: "We are improving 5G capacity this weekend across metropolitan areas.",
  },
  {
    id: "ntf-7",
    ntfId: "NTF-6107",
    audience: "Individual Customer",
    subject: "Add a second business line",
    type: "Email",
    status: "Sent",
    date: "07/08/2026",
    message: "Plan enhancement and speed booster features have been unlocked for your account.",
  },
  {
    id: "ntf-8",
    ntfId: "NTF-6108",
    audience: "Individual Customer",
    subject: "Add a second business line",
    type: "Low",
    status: "Sent",
    date: "07/08/2026",
    message: "Support follow-up confirmation for your recent service inquiry.",
  },
  {
    id: "ntf-9",
    ntfId: "NTF-6109",
    audience: "Individual Customer",
    subject: "Add a second business line",
    type: "Sms",
    status: "Sent",
    date: "07/08/2026",
    message: "Scheduled maintenance will occur tonight between 02:00 and 04:00 AM.",
  },
  {
    id: "ntf-10",
    ntfId: "NTF-6110",
    audience: "Individual Customer",
    subject: "Add a second business line",
    type: "Sms",
    status: "Sent",
    date: "07/08/2026",
    message: "Service renewal reminder: your subscription will auto-renew on the 1st of next month.",
  },
];
