export const INITIAL_PLANS_DATA = [
  {
    id: "plan-1",
    brand: "NovaSky",
    name: "One",
    tagline: "Everything you need for everyday use",
    currency: "CHF",
    price: "24.90",
    period: "/month",
    features: [
      { id: "f1", icon: "radio", text: "25 GB in 5G Switzerland" },
      { id: "f2", icon: "phone", text: "Unlimited Calls within Switzerland" },
      { id: "f3", icon: "message", text: "Unlimited SMS within Switzerland" },
      { id: "f4", icon: "wifi", text: "Hotspot included" },
      { id: "f5", icon: "check", text: "No commitment" },
    ],
  },
  {
    id: "plan-2",
    brand: "NovaSky",
    name: "Plus",
    tagline: "The perfect balance for your everyday life",
    currency: "CHF",
    price: "39.90",
    period: "/month",
    isFeatured: true,
    features: [
      { id: "f1", icon: "radio", text: "80 GB in 5G Switzerland & EU" },
      { id: "f2", icon: "phone", text: "Unlimited Calls within Switzerland" },
      { id: "f3", icon: "message", text: "Unlimited SMS within Switzerland & EU" },
      { id: "f4", icon: "wifi", text: "Hotspot included" },
      { id: "f5", icon: "globe", text: "Roaming in EU included" },
      { id: "f6", icon: "check", text: "No commitment" },
    ],
  },
  {
    id: "plan-3",
    brand: "NovaSky",
    name: "Max",
    tagline: "For those who want the maximum",
    currency: "CHF",
    price: "59.90",
    period: "/month",
    features: [
      { id: "f1", icon: "radio", text: "150 GB in 5G Switzerland" },
      { id: "f2", icon: "phone", text: "Unlimited Calls within Switzerland" },
      { id: "f3", icon: "message", text: "Unlimited SMS within Switzerland & EU" },
      { id: "f4", icon: "wifi", text: "Roaming worldwide included" },
      { id: "f5", icon: "shield", text: "Priority Network" },
    ],
  },
];
