export const CUSTOMERS_DATA = [
  {
    id: "cust-1",
    profileId: "C-1003",
    customer: "Amina Rossi",
    email: "amina.rossi@example.ch",
    phone: "+41 78 441 88 44",
    customerType: "Private",
    plan: "Nova Start",
    usage: "8.5 GB of 25 GB",
    lineStatus: "Active",
    registrationDate: "2026-02-11",
    status: "Active",
    invoice: "INV-9028",
    paymentHistory: "CHF 39.90 paid on 2026-02-11",
  },
  {
    id: "cust-2",
    profileId: "C-1004",
    customer: "Claire Dubois",
    email: "claire.dubois@example.ch",
    phone: "+41 78 884 50 91",
    customerType: "Private",
    plan: "Nova Swiss+",
    usage: "11.2 GB of 40 GB",
    lineStatus: "Active",
    registrationDate: "2026-02-03",
    status: "Active",
    invoice: "INV-9029",
    paymentHistory: "CHF 49.90 paid on 2026-02-03",
  },
  {
    id: "cust-3",
    profileId: "C-1005",
    customer: "Jonas Baumann",
    email: "jonas.baumann@example.ch",
    phone: "+41 77 109 28 72",
    customerType: "Private",
    plan: "Nova Family",
    usage: "35.0 GB of 60 GB",
    lineStatus: "Suspended",
    registrationDate: "2025-11-09",
    status: "Suspended",
    invoice: "INV-9012",
    paymentHistory: "CHF 79.90 paid on 2025-11-09",
  },
  {
    id: "cust-4",
    profileId: "C-1006",
    customer: "Lena Meier",
    email: "lena.meier@example.ch",
    phone: "+41 78 224 11 03",
    customerType: "Private",
    plan: "Nova Swiss+",
    usage: "14.8 GB of 40 GB",
    lineStatus: "Active",
    registrationDate: "2026-01-12",
    status: "Active",
    invoice: "INV-9022",
    paymentHistory: "CHF 49.90 paid on 2026-01-12",
  },
  {
    id: "cust-5",
    profileId: "C-1007",
    customer: "Marco Keller",
    email: "marco.keller@example.ch",
    phone: "+41 78 330 22 18",
    customerType: "Business",
    plan: "Nova Roam",
    usage: "22.4 GB of 50 GB",
    lineStatus: "Active",
    registrationDate: "2025-12-30",
    status: "Active",
    invoice: "INV-9018",
    paymentHistory: "CHF 59.90 paid on 2025-12-30",
  },
  {
    id: "cust-6",
    profileId: "C-1008",
    customer: "Maya Chen",
    email: "maya.chen@example.ch",
    phone: "+41 79 552 14 80",
    customerType: "Private",
    plan: "Nova Start",
    usage: "5.1 GB of 25 GB",
    lineStatus: "Active",
    registrationDate: "2025-10-18",
    status: "Active",
    invoice: "INV-8994",
    paymentHistory: "CHF 39.90 paid on 2025-10-18",
  },
  {
    id: "cust-7",
    profileId: "C-1009",
    customer: "Noah Baker",
    email: "noah.baker@example.ch",
    phone: "+41 76 901 33 55",
    customerType: "Private",
    plan: "Nova Swiss+",
    usage: "19.0 GB of 40 GB",
    lineStatus: "Active",
    registrationDate: "2025-09-24",
    status: "Active",
    invoice: "INV-8980",
    paymentHistory: "CHF 49.90 paid on 2025-09-24",
  },
];

export const STATUS_OPTIONS = ["All", "Active", "Suspended", "Pending"];
export const PLAN_OPTIONS = [
  "All",
  "Nova Start",
  "Nova Swiss+",
  "Nova Family",
  "Nova Roam",
];
export const LINE_STATUS_OPTIONS = ["All", "Active", "Suspended"];

export const CUSTOMER_COLUMNS = [
  { key: "customer", label: "CUSTOMER", className: "font-semibold text-slate-900" },
  { key: "email", label: "EMAIL", className: "text-slate-500" },
  { key: "phone", label: "PHONE", className: "font-mono text-slate-500" },
  { key: "plan", label: "PLAN", className: "font-medium text-slate-600" },
  { key: "lineStatus", label: "LINE STATUS", isStatus: true },
  { key: "registrationDate", label: "REGISTRATION DATE", className: "font-mono text-slate-500" },
  { key: "status", label: "STATUS", isStatus: true },
  { key: "action", label: "ACTIONS", align: "right" },
];

export const CUSTOMER_ACTIONS = [
  { label: "See Details", isPrimary: true, action: "details" },
  { label: "Suspend", action: "suspend" },
  { label: "Active", action: "active" },
];
