export const PLANS = [
  {
    id: "one",
    name: "One",
    tagline: "Everything you need for everyday use",
    price: "24.90",
    currency: "CHF",
    period: "/month",
    popular: false,
    features: [
      { icon: "signal", text: "25 GB in 5G Switzerland" },
      { icon: "phone", text: "Unlimited Calls within Switzerland" },
      { icon: "message", text: "Unlimited SMS within Switzerland" },
      { icon: "wifi", text: "Hotspot included" },
      { icon: "check", text: "No commitment" },
    ],
    cta: { label: "Choose One", path: "/plans/one" },
    detailsPath: "/plans/one",
  },
  {
    id: "plus",
    name: "Plus",
    tagline: "The perfect balance for your everyday life",
    price: "39.90",
    currency: "CHF",
    period: "/month",
    popular: true,
    features: [
      { icon: "signal", text: "80 GB in 5G Switzerland & EU" },
      { icon: "phone", text: "Unlimited Calls within Switzerland" },
      { icon: "message", text: "Unlimited SMS within Switzerland & EU" },
      { icon: "wifi", text: "Hotspot included" },
      { icon: "globe", text: "Roaming in EU included" },
      { icon: "check", text: "No commitment" },
    ],
    cta: { label: "Choose Plus", path: "/plans/plus" },
    detailsPath: "/plans/plus",
  },
  {
    id: "max",
    name: "Max",
    tagline: "For those who want the maximum",
    price: "59.90",
    currency: "CHF",
    period: "/month",
    popular: false,
    features: [
      { icon: "signal", text: "150 GB in 5G Switzerland" },
      { icon: "phone", text: "Unlimited Calls within Switzerland" },
      { icon: "message", text: "Unlimited SMS within Switzerland & EU" },
      { icon: "wifi", text: "Roaming worldwide included" },
      { icon: "check", text: "Priority Network" },
    ],
    cta: { label: "Choose Max", path: "/plans/max" },
    detailsPath: "/plans/max",
  },
];

export const getPlanById = (id) => PLANS.find((plan) => plan.id === id);
