export const USER_PAYMENTS = {
  header: {
    title: "Payments",
    subtitle: "Pay your bills or top up your line securely.",
  },
  tabs: [
    { id: "make-payment", label: "Make a payment" },
    { id: "automatic-payments", label: "Automatic payments" },
    { id: "payment-history", label: "Payment history" },
  ],
  paymentTypes: [
    {
      id: "bill",
      title: "My bill",
      subtitle: "Pay your monthly bill",
      icon: "bill",
    },
    {
      id: "topup",
      title: "Top up my line",
      subtitle: "Add credit to my balance",
      icon: "smartphone",
    },
  ],
  bills: [
    {
      id: "bill-jul-2024",
      month: "July 2024",
      issueDate: "July 10, 2024",
      dueDate: "July 10, 2024",
      period: "Jul 01 - Jul 31, 2024",
      amount: "34.90",
      status: "Paid",
      statusText: "Paid on July 10, 2024",
      invoiceNumber: "INV-2024-07-8891",
      breakdown: {
        planName: "Nova Unlimited 5G (Switzerland + EU)",
        baseAmount: "29.90",
        options: [
          { name: "Extra High-Speed Data (5 GB)", amount: "5.00" },
        ],
        vatPercent: "8.1%",
        vatAmount: "2.62",
        total: "34.90",
      },
    },
    {
      id: "bill-aug-2024",
      month: "August 2024",
      issueDate: "August 10, 2024",
      dueDate: "August 25, 2024",
      period: "Aug 01 - Aug 31, 2024",
      amount: "34.90",
      status: "Pending",
      statusText: "Due on August 25, 2024",
      invoiceNumber: "INV-2024-08-9102",
      breakdown: {
        planName: "Nova Unlimited 5G (Switzerland + EU)",
        baseAmount: "29.90",
        options: [
          { name: "Extra High-Speed Data (5 GB)", amount: "5.00" },
        ],
        vatPercent: "8.1%",
        vatAmount: "2.62",
        total: "34.90",
      },
    },
    {
      id: "bill-jun-2024",
      month: "June 2024",
      issueDate: "June 10, 2024",
      dueDate: "June 10, 2024",
      period: "Jun 01 - Jun 30, 2024",
      amount: "34.90",
      status: "Paid",
      statusText: "Paid on June 10, 2024",
      invoiceNumber: "INV-2024-06-7643",
      breakdown: {
        planName: "Nova Unlimited 5G (Switzerland + EU)",
        baseAmount: "29.90",
        options: [
          { name: "Extra High-Speed Data (5 GB)", amount: "5.00" },
        ],
        vatPercent: "8.1%",
        vatAmount: "2.62",
        total: "34.90",
      },
    },
  ],
  topUpOptions: [
    { amount: "10.00", bonus: null },
    { amount: "20.00", bonus: null },
    { amount: "30.00", bonus: "+ CHF 2 bonus credit" },
    { amount: "50.00", bonus: "+ CHF 5 bonus credit", popular: true },
    { amount: "100.00", bonus: "+ CHF 15 bonus credit" },
  ],
  paymentMethods: [
    {
      id: "pm-visa-4242",
      type: "card",
      brand: "visa",
      title: "Visa **** 4242",
      expiry: "12/26",
      isDefault: true,
      holder: "Thomas Müller",
    },
    {
      id: "pm-mc-8888",
      type: "card",
      brand: "mastercard",
      title: "Mastercard **** 8888",
      expiry: "08/25",
      isDefault: false,
      holder: "Thomas Müller",
    },
    {
      id: "pm-twint",
      type: "twint",
      brand: "twint",
      title: "TWINT",
      expiry: null,
      isDefault: false,
      holder: "+41 79 123 45 67",
    },
    {
      id: "pm-apple-pay",
      type: "apple-pay",
      brand: "apple-pay",
      title: "Apple Pay",
      expiry: null,
      isDefault: false,
      holder: "Apple Wallet",
    },
  ],
  securityGuarantees: [
    "100% secure payment",
    "Encrypted data",
    "PCI DSS compliant",
    "No banking data stored",
  ],
  helpLinks: [
    {
      id: "help-1",
      title: "Live chat",
      subtitle: "Chat with an advisor",
      icon: "chat",
    },
    {
      id: "help-2",
      title: "Help Center",
      subtitle: "Find answers",
      icon: "help",
    },
    {
      id: "help-3",
      title: "Call us",
      subtitle: "0800 800 100",
      icon: "phone",
    },
  ],
  automaticPayments: {
    enabled: true,
    frequency: "Monthly",
    debitDay: "1st of every month",
    nextDebitDate: "1 August 2026",
    estimatedAmount: "CHF 84.90",
    activeMethodId: "pm-mastercard-9043",
    notifyBeforeDays: 3,
    sendEmailReceipt: true,
    sendSmsAlert: true,
  },
  historyStats: {
    totalPaid: "CHF 506.10",
    totalPaidPeriod: "Last 12 months",
    pendingCount: 1,
    pendingSub: "CHF 84.90 due 15 Jul",
    failedCount: 1,
    failedSub: "Retry available",
    lastPaymentAmount: "CHF 84.90",
    lastPaymentSub: "01 Jun 2026 • Mastercard",
  },
  paymentHistory: [
    {
      id: "NS-2026-004182",
      invoice: "NS-2026-004182",
      date: "01 Jul 2026",
      amount: "84.90",
      method: "Visa •••• 4821",
      brand: "visa",
      status: "Pending",
      type: "Monthly Bill",
    },
    {
      id: "NS-2026-003977",
      invoice: "NS-2026-003977",
      date: "01 Jun 2026",
      amount: "84.90",
      method: "Mastercard •••• 9043",
      brand: "mastercard",
      status: "Paid",
      type: "Monthly Bill",
    },
    {
      id: "NS-2026-003741",
      invoice: "NS-2026-003741",
      date: "01 May 2026",
      amount: "92.40",
      method: "TWINT",
      brand: "twint",
      status: "Paid",
      type: "Monthly Bill + Roaming",
    },
    {
      id: "NS-2026-003512",
      invoice: "NS-2026-003512",
      date: "01 Apr 2026",
      amount: "84.90",
      method: "Apple Pay",
      brand: "apple-pay",
      status: "Failed",
      type: "Monthly Bill",
    },
    {
      id: "NS-2026-003288",
      invoice: "NS-2026-003288",
      date: "01 Mar 2026",
      amount: "84.90",
      method: "Mastercard •••• 9043",
      brand: "mastercard",
      status: "Paid",
      type: "Monthly Bill",
    },
    {
      id: "NS-2026-003044",
      invoice: "NS-2026-003044",
      date: "01 Feb 2026",
      amount: "79.50",
      method: "Visa •••• 4821",
      brand: "visa",
      status: "Paid",
      type: "Monthly Bill",
    },
    {
      id: "NS-2026-002819",
      invoice: "NS-2026-002819",
      date: "01 Jan 2026",
      amount: "79.50",
      method: "Visa •••• 4821",
      brand: "visa",
      status: "Paid",
      type: "Monthly Bill",
    },
    {
      id: "NS-2025-002590",
      invoice: "NS-2025-002590",
      date: "01 Dec 2025",
      amount: "79.50",
      method: "Visa •••• 4821",
      brand: "visa",
      status: "Paid",
      type: "Monthly Bill",
    },
  ],
};
