export const USER_PLANS_OPTIONS = {
  tabs: [
    { id: "change-plan", label: "Change Plan" },
    { id: "add-options", label: "Add Options" },
    { id: "roaming", label: "Roaming" },
    { id: "data-boosters", label: "Data Boosters" },
    { id: "intl-calls", label: "International Calls" },
    { id: "services", label: "Services" },
  ],
  currentPlan: {
    name: "NovaSky Plus",
    networkBadge: "5G",
    price: "34.90",
    renewDate: "August 07, 2024",
    renewHint: "13 days left",
    features: [
      { id: "data", value: "80 GB", label: "DATA", icon: "barChart" },
      { id: "calls", value: "Unlimited", label: "CALLS", icon: "phone" },
      { id: "sms", value: "Unlimited", label: "SMS", icon: "message" },
      { id: "roaming", value: "Included", label: "ROAMING", icon: "globe" },
      { id: "voicemail", value: "Included", label: "VOICEMAIL", icon: "voicemail" },
      { id: "hotspot", value: "Included", label: "HOTSPOT", icon: "wifi" },
    ],
  },
  plans: [
    {
      id: "one",
      name: "NovaSky One",
      networkBadge: "4G",
      price: "24.90",
      features: [
        { label: "25 GB Data" },
        { label: "Unlimited Calls" },
        { label: "Unlimited SMS" },
        { label: "Included Voicemail" },
        { label: "Included Hotspot" },
      ],
      isCurrent: false,
    },
    {
      id: "plus",
      name: "NovaSky Plus",
      networkBadge: "5G",
      price: "34.90",
      isPopular: true,
      features: [
        { label: "80 GB Data" },
        { label: "Unlimited Calls" },
        { label: "Unlimited SMS" },
        { label: "Included Voicemail" },
        { label: "Included Hotspot" },
      ],
      isCurrent: true,
    },
    {
      id: "max",
      name: "NovaSky Max",
      networkBadge: "5G",
      price: "59.90",
      features: [
        { label: "80 GB Data" },
        { label: "Unlimited Calls" },
        { label: "Unlimited SMS" },
        { label: "Included Voicemail" },
        { label: "Included Hotspot" },
        { label: "Priority Network" },
      ],
      isCurrent: false,
    },
  ],
  quickAdd: [
    {
      id: "booster",
      title: "Data Booster +10GB",
      description: "+10 GB / 30 days",
      price: "9.90",
      icon: "wifi",
    },
    {
      id: "social",
      title: "Unlimited Social",
      description: "Valid for 30 Days",
      price: "4.90",
      icon: "social",
    },
    {
      id: "intl",
      title: "International calls 100 min",
      description: "Valid for 30 days",
      price: "7.90",
      icon: "phone",
    },
    {
      id: "hotspot",
      title: "Hotspot 20 GB",
      description: "Valid for 30 days",
      price: "6.90",
      icon: "wifi",
    },
  ],
  whyUpgrade: [
    {
      id: "data",
      title: "More data",
      description: "Enjoy more high-speed data for streaming and browsing.",
      icon: "zap",
    },
    {
      id: "experience",
      title: "Better experience",
      description: "Access our best network and premium services.",
      icon: "star",
    },
    {
      id: "flexibility",
      title: "Flexibility",
      description: "Change or upgrade your plan anytime.",
      icon: "refresh",
    },
  ],
  needHelp: [
    {
      id: "compare",
      title: "Compare all plans",
      description: "See all features and differences",
      icon: "chart",
    },
    {
      id: "guide",
      title: "Plan change guide",
      description: "How to change your plan",
      icon: "doc",
    },
    {
      id: "chat",
      title: "Chat with us",
      description: "Speak with an advisor",
      icon: "chat",
    },
  ],
};
