export const USER_USAGE = {
  currentPlan: {
    name: "NovaSky Plus",
    networkBadge: "5G",
    renewDate: "August 07, 2024",
    renewDays: 13,
    renewTime: "00:00",
  },
  usageSummary: {
    usedData: 38.2,
    totalData: 80,
    remainingData: 41.8,
    usedPercentage: 47,
    includedHotspot: 0,
    roamingUsageText: "You haven't used any data while roaming.",
  },
  boosters: [
    { id: "b-1", amount: "+5 GB", validity: "Valid for 30 days", price: "5.90" },
    { id: "b-2", amount: "+10 GB", validity: "Valid for 30 days", price: "9.90" },
    { id: "b-3", amount: "+20 GB", validity: "Valid for 30 days", price: "16.90" },
    { id: "b-4", amount: "+50 GB", validity: "Valid for 30 days", price: "29.90" },
  ],
  sidebarSummary: [
    { id: "data", label: "Data", value: "38.2 / 80 GB", percent: 47, style: "bg-btnPrimary", icon: "wifi" },
    { id: "calls", label: "Calls", value: "Unlimited", percent: 100, style: "bg-emerald-500", icon: "phone" },
    { id: "sms", label: "SMS", value: "Unlimited", percent: 100, style: "bg-purple-500", icon: "message" },
    { id: "hotspot", label: "Hotspot", value: "Included →", percent: 100, isLink: true, icon: "wifi" },
  ],
  activeOptions: [
    { id: "opt-1", name: "Europe Roaming", status: "Active", icon: "globe" },
    { id: "opt-2", name: "International Calls", status: "Active", icon: "phone" },
    { id: "opt-3", name: "Visual Voicemail", status: "Active", icon: "voicemail" },
  ],
  helpLinks: [
    { id: "h-1", title: "Live Chat", subtitle: "Chat with an advisor", icon: "chat" },
    { id: "h-2", title: "Help Center", subtitle: "Find answers to your questions", icon: "help" },
    { id: "h-3", title: "Call us", subtitle: "0800 800 100", icon: "phone" },
  ],
  callSummary: {
    planName: "NovaSky Plus",
    networkBadge: "5G Ultra Network Access",
    voiceUsage: "Unlimited",
    extraCost: "0.00 CHF Extra",
    voiceUsageLabel: "Unlimited Minutes Used",
    intlCalls: "Included (Zone 1)",
    intlCallsLabel: "EU, UK & EFTA Covered",
  },
  recentCalls: [
    {
      id: "call-1",
      name: "Elena Rostova",
      countryCode: "CH",
      number: "+41 78 923 11 04",
      location: "Switzerland",
      type: "outgoing",
      duration: "14 min 32 sec",
      timestamp: "Today, Jul 31 at 18:42",
    },
    {
      id: "call-2",
      name: "Dr. Lukas Weber",
      countryCode: "CH",
      number: "+41 44 211 40 00",
      location: "Switzerland",
      type: "incoming",
      duration: "03 min 12 sec",
      timestamp: "Today, Jul 31 at 14:15",
    },
    {
      id: "call-3",
      name: "Matteo Moretti",
      countryCode: "IT",
      number: "+39 02 892 1102",
      location: "Italy (EU Zone 1)",
      type: "outgoing",
      duration: "28 min 45 sec",
      timestamp: "Yesterday, Jul 30 at 20:10",
    },
    {
      id: "call-4",
      name: "Sophie Dubois",
      countryCode: "FR",
      number: "+33 1 42 68 55 00",
      location: "France (EU Zone 1)",
      type: "incoming",
      duration: "09 min 20 sec",
      timestamp: "Jul 29, 2026 at 11:05",
    },
    {
      id: "call-5",
      name: "Zurich Office Desk",
      countryCode: "CH",
      number: "+41 44 800 99 88",
      location: "Switzerland",
      type: "outgoing",
      duration: "45 min 00 sec",
      timestamp: "Jul 28, 2026 at 09:30",
    },
    {
      id: "call-6",
      name: "Michael Schmidt (Berlin)",
      countryCode: "DE",
      number: "+49 30 123 4567",
      location: "Germany (EU Zone 1)",
      type: "outgoing",
      duration: "18 min 08 sec",
      timestamp: "Jul 27, 2026 at 16:55",
    },
  ],
};
