export const USER_SECURITY = {
  header: {
    title: "Security",
    subtitle: "Protect your account and your personal data.",
  },
  banner: {
    title: "Strengthen your account security.",
    subtitle: "We recommend enabling all available security options.",
  },
  settings: [
    {
      id: "2fa",
      title: "Two-Factor Authentication (2FA)",
      description: "Add an extra layer of security to your account.",
      status: "Enabled",
      statusVariant: "green",
      icon: "shield",
    },
    {
      id: "password",
      title: "Password",
      description: "Choose a strong password to protect your account.",
      status: "Up to Date",
      statusVariant: "green",
      icon: "key",
    },
    {
      id: "recovery-email",
      title: "Recovery Email",
      description: "Used to reset your password or receive security alerts.",
      status: "Verified",
      statusVariant: "green",
      extraInfo: "abdoulaye.sow@email.com",
      icon: "mail",
    },
    {
      id: "phone-number",
      title: "Phone Number",
      description: "Used for verification and account recovery.",
      status: "Verified",
      statusVariant: "green",
      extraInfo: "+41 76 123 45 67",
      icon: "phone",
    },
    {
      id: "device-management",
      title: "Device Management",
      description: "View and manage the devices connected to your account.",
      status: "3 Devices",
      statusVariant: "blue",
      icon: "monitor",
    },
    {
      id: "login-alerts",
      title: "Login Alerts",
      description: "Receive a notification for every new login.",
      status: "Enabled",
      statusVariant: "green",
      icon: "bell",
    },
    {
      id: "delete-account",
      title: "Delete My Account",
      description: "Permanently delete your account and all your data.",
      status: "Disabled",
      statusVariant: "red",
      icon: "trash",
    },
  ],
  securityLevel: {
    title: "Security level",
    message: "Your account is well protected. Keep it up!",
    checklist: [
      "Two-factor authentication enabled",
      "Secure password",
      "Email and phone number verified",
      "Login alerts enabled",
    ],
    lastCheck: "Today, 09:41",
  },
  connectedDevices: [
    {
      id: "dev-1",
      name: "iPhone 14 Pro",
      location: "Fribourg, Switzerland",
      os: "iOS 17.5",
      isCurrent: true,
      icon: "smartphone",
    },
    {
      id: "dev-2",
      name: "MacBook Pro",
      location: "Fribourg, Switzerland",
      os: "macOS 14.4",
      lastActive: "2 hours ago",
      isCurrent: false,
      icon: "laptop",
    },
    {
      id: "dev-3",
      name: "Samsung Galaxy S23",
      location: "Lausanne, Switzerland",
      os: "Android 14",
      lastActive: "Yesterday, 18:22",
      isCurrent: false,
      icon: "smartphone",
    },
  ],
  helpLinks: [
    {
      id: "safety-tips",
      title: "Safety tips",
      subtitle: "Discover our tips for securing your account",
      icon: "shield",
    },
    {
      id: "help-center",
      title: "Help Center",
      subtitle: "Find answers to your questions",
      icon: "clock",
      to: "/dashboard/user/support",
    },
    {
      id: "contact-us",
      title: "Contact us",
      subtitle: "Speak with an advisor",
      icon: "message",
      to: "/dashboard/user/support",
    },
  ],
};
