export const USER_OVERVIEW = {
  subtitle: "Manage your line and make the most of your NovaSky experience.",
  mainLine: {
    label: "My main line",
    status: "ACTIVE",
    phone: "+41 76 123 4567",
    plan: "NovaSky Plus Plan",
    nextBillingDate: "August 07, 2024",
    nextBillingHint: "In 17 days",
    balance: "CHF 0.00",
    balanceStatus: "Up to date",
    managePath: "/dashboard/user/my-line",
  },
  usage: {
    detailsPath: "/dashboard/user/usage",
    renewMessage: "Your plan will renew on August 07, 2024 at 00:00.",
    items: [
      {
        id: "data",
        label: "Data",
        value: "32.2 GB / 80 GB",
        remainingLabel: "Remaining",
        progress: 47,
        progressColor: "bg-emerald-500",
        hint: "47% used",
      },
      {
        id: "calls",
        label: "Calls",
        value: "Unlimited",
        remainingLabel: "Remaining",
        progress: 100,
        progressColor: "bg-btnPrimary",
        hint: "Unlimited calls",
      },
      {
        id: "sms",
        label: "SMS",
        value: "Unlimited",
        remainingLabel: "Remaining",
        progress: 100,
        progressColor: "bg-violet-500",
        hint: "Unlimited SMS",
      },
    ],
  },
  latestBill: {
    seeAllPath: "/dashboard/user/bills",
    month: "July 2024",
    status: "Paid",
    amount: "CHF 34.90",
    paidOn: "Paid on July 10, 2024",
  },
  offers: {
    seeAllPath: "/dashboard/user/plans-options",
    items: [
      {
        id: "data-pack",
        title: "+20 GB",
        subtitle: "Mobile data",
        price: "CHF 9.90",
        iconBg: "bg-emerald-50",
        iconColor: "text-emerald-600",
        icon: "link",
      },
      {
        id: "roaming",
        title: "EuropeRoaming",
        subtitle: "1 GB / 7 days",
        price: "CHF 12.90",
        iconBg: "bg-sky-50",
        iconColor: "text-sky-600",
        icon: "globe",
      },
      {
        id: "calls",
        title: "International Calls",
        subtitle: "500 min",
        price: "CHF 7.90",
        iconBg: "bg-violet-50",
        iconColor: "text-violet-600",
        icon: "infinity",
      },
    ],
  },
  premium: {
    title: "Premium Level",
    description: "You're enjoying Premium benefits",
    linkLabel: "See my benefits",
    path: "/dashboard/user/plans-options",
  },
  quickActions: [
    { id: "top-up", label: "Top up", icon: "wallet", path: "/dashboard/user/payments" },
    { id: "option", label: "Buy an option", icon: "package", path: "/dashboard/user/plans-options" },
    { id: "esim-1", label: "Get an e-sim", icon: "sim", path: "/dashboard/user/esim" },
    { id: "esim-2", label: "Get an e-sim", icon: "sim", path: "/dashboard/user/esim" },
    { id: "support", label: "Support", icon: "headset", path: "/dashboard/user/support" },
  ],
  promo: {
    title: "More data for your adventures?",
    description: "Add an option in just a few clicks to stay connected.",
    cta: "Discover our options",
    path: "/dashboard/user/plans-options",
  },
  help: {
    seeAllPath: "/dashboard/user/support",
    items: [
      {
        id: "chat",
        title: "Chat with us",
        description: "Speak with an advisor",
        icon: "message",
      },
      {
        id: "whatsapp",
        title: "WhatsApp",
        description: "Message us on WhatsApp",
        icon: "whatsapp",
      },
      {
        id: "help-center",
        title: "Help center",
        description: "Find answers to your questions",
        icon: "help",
      },
    ],
  },
};
