export const USER_PAYMENTS = {
  header: {
    title: "Payments",
    subtitle: "Pay your bills or top up your line securely.",
  },
  tabs: [
    { id: "make-payment", label: "Make a payment" },
    { id: "automatic-payments", label: "Automatic payments" },
    { id: "payment-history", label: "Payment history" },
  ],
  paymentTypes: [
    {
      id: "bill",
      title: "My bill",
      subtitle: "Pay your monthly bill",
      icon: "bill",
    },
    {
      id: "topup",
      title: "Top up my line",
      subtitle: "Add credit to my balance",
      icon: "smartphone",
    },
  ],
  bills: [
    {
      id: "bill-jul-2024",
      month: "July 2024",
      issueDate: "July 10, 2024",
      dueDate: "July 10, 2024",
      period: "Jul 01 - Jul 31, 2024",
      amount: "34.90",
      status: "Paid",
      statusText: "Paid on July 10, 2024",
      invoiceNumber: "INV-2024-07-8891",
      breakdown: {
        planName: "Nova Unlimited 5G (Switzerland + EU)",
        baseAmount: "29.90",
        options: [
          { name: "Extra High-Speed Data (5 GB)", amount: "5.00" },
        ],
        vatPercent: "8.1%",
        vatAmount: "2.62",
        total: "34.90",
      },
    },
    {
      id: "bill-aug-2024",
      month: "August 2024",
      issueDate: "August 10, 2024",
      dueDate: "August 25, 2024",
      period: "Aug 01 - Aug 31, 2024",
      amount: "34.90",
      status: "Pending",
      statusText: "Due on August 25, 2024",
      invoiceNumber: "INV-2024-08-9102",
      breakdown: {
        planName: "Nova Unlimited 5G (Switzerland + EU)",
        baseAmount: "29.90",
        options: [
          { name: "Extra High-Speed Data (5 GB)", amount: "5.00" },
        ],
        vatPercent: "8.1%",
        vatAmount: "2.62",
        total: "34.90",
      },
    },
    {
      id: "bill-jun-2024",
      month: "June 2024",
      issueDate: "June 10, 2024",
      dueDate: "June 10, 2024",
      period: "Jun 01 - Jun 30, 2024",
      amount: "34.90",
      status: "Paid",
      statusText: "Paid on June 10, 2024",
      invoiceNumber: "INV-2024-06-7643",
      breakdown: {
        planName: "Nova Unlimited 5G (Switzerland + EU)",
        baseAmount: "29.90",
        options: [
          { name: "Extra High-Speed Data (5 GB)", amount: "5.00" },
        ],
        vatPercent: "8.1%",
        vatAmount: "2.62",
        total: "34.90",
      },
    },
  ],
  topUpOptions: [
    { amount: "10.00", bonus: null },
    { amount: "20.00", bonus: null },
    { amount: "30.00", bonus: "+ CHF 2 bonus credit" },
    { amount: "50.00", bonus: "+ CHF 5 bonus credit", popular: true },
    { amount: "100.00", bonus: "+ CHF 15 bonus credit" },
  ],
  paymentMethods: [
    {
      id: "pm-visa-4242",
      type: "card",
      brand: "visa",
      title: "Visa **** 4242",
      expiry: "12/26",
      isDefault: true,
      holder: "Thomas Müller",
    },
    {
      id: "pm-mc-8888",
      type: "card",
      brand: "mastercard",
      title: "Mastercard **** 8888",
      expiry: "08/25",
      isDefault: false,
      holder: "Thomas Müller",
    },
    {
      id: "pm-twint",
      type: "twint",
      brand: "twint",
      title: "TWINT",
      expiry: null,
      isDefault: false,
      holder: "+41 79 123 45 67",
    },
    {
      id: "pm-apple-pay",
      type: "apple-pay",
      brand: "apple-pay",
      title: "Apple Pay",
      expiry: null,
      isDefault: false,
      holder: "Apple Wallet",
    },
  ],
  securityGuarantees: [
    "100% secure payment",
    "Encrypted data",
    "PCI DSS compliant",
    "No banking data stored",
  ],
  helpLinks: [
    {
      id: "help-1",
      title: "Live chat",
      subtitle: "Chat with an advisor",
      icon: "chat",
    },
    {
      id: "help-2",
      title: "Help Center",
      subtitle: "Find answers",
      icon: "help",
    },
    {
      id: "help-3",
      title: "Call us",
      subtitle: "0800 800 100",
      icon: "phone",
    },
  ],
  automaticPayments: {
    enabled: true,
    frequency: "Monthly",
    debitDay: "10th of every month",
    nextDebitDate: "August 10, 2024",
    estimatedAmount: "CHF 34.90",
    activeMethodId: "pm-visa-4242",
    notifyBeforeDays: 3,
    sendEmailReceipt: true,
    sendSmsAlert: true,
  },
  paymentHistory: [
    {
      id: "TXN-2024-0710-01",
      date: "July 10, 2024, 09:14 AM",
      description: "Bill payment - July 2024",
      method: "Visa **** 4242",
      brand: "visa",
      amount: "34.90",
      status: "Successful",
      invoiceRef: "INV-2024-07-8891",
    },
    {
      id: "TXN-2024-0610-02",
      date: "June 10, 2024, 09:12 AM",
      description: "Bill payment - June 2024",
      method: "Visa **** 4242",
      brand: "visa",
      amount: "34.90",
      status: "Successful",
      invoiceRef: "INV-2024-06-7643",
    },
    {
      id: "TXN-2024-0522-03",
      date: "May 22, 2024, 03:45 PM",
      description: "Prepaid Balance Top Up",
      method: "TWINT",
      brand: "twint",
      amount: "20.00",
      status: "Successful",
      invoiceRef: "TOP-2024-05-3312",
    },
    {
      id: "TXN-2024-0510-04",
      date: "May 10, 2024, 09:15 AM",
      description: "Bill payment - May 2024",
      method: "Visa **** 4242",
      brand: "visa",
      amount: "34.90",
      status: "Successful",
      invoiceRef: "INV-2024-05-6521",
    },
    {
      id: "TXN-2024-0410-05",
      date: "April 10, 2024, 09:10 AM",
      description: "Bill payment - April 2024",
      method: "Mastercard **** 8888",
      brand: "mastercard",
      amount: "34.90",
      status: "Successful",
      invoiceRef: "INV-2024-04-5410",
    },
    {
      id: "TXN-2024-0310-06",
      date: "March 10, 2024, 09:11 AM",
      description: "Bill payment - March 2024",
      method: "Mastercard **** 8888",
      brand: "mastercard",
      amount: "34.90",
      status: "Successful",
      invoiceRef: "INV-2024-03-4399",
    },
  ],
};
