export const IDENTITY_DATA = [
  {
    id: "id-1",
    customer: "Marc Dubois",
    verificationId: "V-8841",
    relatedOrder: "NS-240618-047",
    documentType: "National ID Card",
    documentTypeRaw: "National_ID_Card",
    uploadedIdType: "Swiss identity card",
    submittedDate: "07/08/2026",
    submittedTime: "18 Jun 2024, 08:32",
    status: "Rejected",
    comment: "",
  },
  {
    id: "id-2",
    customer: "Albert Flores",
    verificationId: "V-8842",
    relatedOrder: "NS-240618-048",
    documentType: "National ID Card",
    documentTypeRaw: "National_ID_Card",
    uploadedIdType: "National identity card",
    submittedDate: "07/08/2026",
    submittedTime: "07 Aug 2026, 09:15",
    status: "Pending",
    comment: "",
  },
  {
    id: "id-3",
    customer: "Marvin McKinney",
    verificationId: "V-8843",
    relatedOrder: "NS-240618-049",
    documentType: "Driving License",
    documentTypeRaw: "Driving_License",
    uploadedIdType: "Driving license (Class B)",
    submittedDate: "07/08/2026",
    submittedTime: "07 Aug 2026, 10:20",
    status: "Approved",
    comment: "",
  },
  {
    id: "id-4",
    customer: "Dianne Russell",
    verificationId: "V-8844",
    relatedOrder: "NS-240618-050",
    documentType: "Driving License",
    documentTypeRaw: "Driving_License",
    uploadedIdType: "Driving license",
    submittedDate: "07/08/2026",
    submittedTime: "07 Aug 2026, 11:05",
    status: "Approved",
    comment: "",
  },
  {
    id: "id-5",
    customer: "Cameron Williamson",
    verificationId: "V-8845",
    relatedOrder: "NS-240618-051",
    documentType: "Driving License",
    documentTypeRaw: "Driving_License",
    uploadedIdType: "Driving license",
    submittedDate: "07/08/2026",
    submittedTime: "07 Aug 2026, 11:45",
    status: "Approved",
    comment: "",
  },
  {
    id: "id-6",
    customer: "Robert Fox",
    verificationId: "V-8846",
    relatedOrder: "NS-240618-052",
    documentType: "National ID Card",
    documentTypeRaw: "National_ID_Card",
    uploadedIdType: "National identity card",
    submittedDate: "07/08/2026",
    submittedTime: "07 Aug 2026, 12:30",
    status: "Pending",
    comment: "",
  },
  {
    id: "id-7",
    customer: "Jane Cooper",
    verificationId: "V-8847",
    relatedOrder: "NS-240618-053",
    documentType: "National ID Card",
    documentTypeRaw: "National_ID_Card",
    uploadedIdType: "National identity card",
    submittedDate: "07/08/2026",
    submittedTime: "07 Aug 2026, 13:10",
    status: "Rejected",
    comment: "",
  },
  {
    id: "id-8",
    customer: "Brooklyn Simmons",
    verificationId: "V-8848",
    relatedOrder: "NS-240618-054",
    documentType: "National ID Card",
    documentTypeRaw: "National_ID_Card",
    uploadedIdType: "National identity card",
    submittedDate: "07/08/2026",
    submittedTime: "07 Aug 2026, 14:00",
    status: "Rejected",
    comment: "",
  },
  {
    id: "id-9",
    customer: "Wade Warren",
    verificationId: "V-8849",
    relatedOrder: "NS-240618-055",
    documentType: "Driving License",
    documentTypeRaw: "Driving_License",
    uploadedIdType: "Driving license",
    submittedDate: "07/08/2026",
    submittedTime: "07 Aug 2026, 15:20",
    status: "Pending",
    comment: "",
  },
  {
    id: "id-10",
    customer: "Jerome Bell",
    verificationId: "V-8850",
    relatedOrder: "NS-240618-056",
    documentType: "National ID Card",
    documentTypeRaw: "National_ID_Card",
    uploadedIdType: "National identity card",
    submittedDate: "07/08/2026",
    submittedTime: "07 Aug 2026, 16:40",
    status: "Pending",
    comment: "",
  },
  {
    id: "id-11",
    customer: "Jacob Jones",
    verificationId: "V-8851",
    relatedOrder: "NS-240618-057",
    documentType: "Driving License",
    documentTypeRaw: "Driving_License",
    uploadedIdType: "Driving license",
    submittedDate: "07/08/2026",
    submittedTime: "07 Aug 2026, 17:15",
    status: "Pending",
    comment: "",
  },
];

export const IDENTITY_COLUMNS = [
  { key: "customer", label: "Customer", className: "font-medium text-slate-900" },
  { key: "documentType", label: "Document Type", className: "text-slate-600" },
  { key: "submittedDate", label: "Submitted Date", className: "font-mono text-slate-600" },
  { key: "status", label: "Status", isStatus: true },
  { key: "action", label: "Action", align: "center" },
];

export const IDENTITY_ACTIONS = [
  { label: "See Details", isPrimary: true, action: "details" },
  { label: "Pending", action: "status_pending" },
  { label: "Approved", action: "status_approved" },
  { label: "Rejected", action: "status_rejected" },
];

export const IDENTITY_STATUS_FILTERS = [
  "All Statuses",
  "Pending",
  "Approved",
  "Rejected",
];
