export const COLLABORATOR_NOTIFICATIONS_DATA = [
  {
    id: "notif-1",
    type: "activation",
    title: "Activation Complete",
    description: "John Smith's eSIM activation is complete.",
    timeAgo: "2 min ago",
    unread: true,
  },
  {
    id: "notif-2",
    type: "order",
    title: "New Order Submitted",
    description: "Marco Rossi's NovaSky One order has been submitted.",
    timeAgo: "1 hr ago",
    unread: true,
  },
  {
    id: "notif-3",
    type: "commission",
    title: "Commission Payment Processed",
    description: "CHF 150.00 commission payment has been processed.",
    timeAgo: "3 hrs ago",
    unread: true,
  },
  {
    id: "notif-4",
    type: "order",
    title: "Order Processing",
    description: "Sophie Bernard's Physical SIM order is being processed.",
    timeAgo: "5 hrs ago",
    unread: false,
  },
  {
    id: "notif-5",
    type: "system",
    title: "System Maintenance",
    description: "Scheduled maintenance on Aug 20, 2026 from 02:00–04:00 CET.",
    timeAgo: "1 day ago",
    unread: false,
  },
  {
    id: "notif-6",
    type: "activation",
    title: "Activation Started",
    description: "Thomas Weber's eSIM activation has started.",
    timeAgo: "2 days ago",
    unread: false,
  },
  {
    id: "notif-7",
    type: "activation",
    title: "Activation Started",
    description: "Thomas Weber's eSIM activation has started.",
    timeAgo: "2 days ago",
    unread: false,
  },
  {
    id: "notif-8",
    type: "activation",
    title: "Activation Started",
    description: "Thomas Weber's eSIM activation has started.",
    timeAgo: "2 days ago",
    unread: false,
  },
  {
    id: "notif-9",
    type: "activation",
    title: "Activation Started",
    description: "Thomas Weber's eSIM activation has started.",
    timeAgo: "2 days ago",
    unread: false,
  },
  {
    id: "notif-10",
    type: "activation",
    title: "Activation Started",
    description: "Thomas Weber's eSIM activation has started.",
    timeAgo: "2 days ago",
    unread: false,
  },
  {
    id: "notif-11",
    type: "activation",
    title: "Activation Started",
    description: "Thomas Weber's eSIM activation has started.",
    timeAgo: "2 days ago",
    unread: false,
  },
  {
    id: "notif-12",
    type: "activation",
    title: "Activation Started",
    description: "Thomas Weber's eSIM activation has started.",
    timeAgo: "2 days ago",
    unread: false,
  },
  {
    id: "notif-13",
    type: "activation",
    title: "Activation Started",
    description: "Thomas Weber's eSIM activation has started.",
    timeAgo: "2 days ago",
    unread: false,
  },
  {
    id: "notif-14",
    type: "activation",
    title: "Activation Started",
    description: "Thomas Weber's eSIM activation has started.",
    timeAgo: "2 days ago",
    unread: false,
  },
  {
    id: "notif-15",
    type: "activation",
    title: "Activation Started",
    description: "Thomas Weber's eSIM activation has started.",
    timeAgo: "2 days ago",
    unread: false,
  },
];
